Try using with_mounted_file but get error
(venv) luke@mind:~/pd/hello-dagger$ python ci/main.py
Connected to engine 5c8948c1381d

------
 > host.file /var/run/docker.sock:
------
Traceback (most recent call last):
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/dagger/api/base.py", line 170, in _handle_execute
    yield
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/dagger/api/base.py", line 107, in execute
    result = await self.session.execute(query)
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/gql/client.py", line 1231, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'error from sender: open /run/containerd: permission denied', 'locations': [{'line': 12, 'column': 13}], 'path': ['container', 'from', 'withMountedFile', 'withEnvVariable', 'withExec', 'stdout']}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luke/pd/hello-dagger/ci/main.py", line 41, in <module>
    anyio.run(main)
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 199, in wrapper
    return await func(*args)
  File "/home/luke/pd/hello-dagger/ci/main.py", line 34, in main
    version = await python.stdout()
  File "<@beartype(dagger.api.gen.Container.stdout) at 0x7fe06c3a0820>", line 10, in stdout
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/dagger/api/gen.py", line 822, in stdout
    return await _ctx.execute(str)
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/dagger/api/base.py", line 106, in execute
    with self._handle_execute(query):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/luke/pd/hello-dagger/venv/lib/python3.10/site-packages/dagger/api/base.py", line 196, in _handle_execute
    raise error from e
dagger.exceptions.QueryError: error from sender: open /run/containerd: permission denied